FROM fluent/fluentd:latest

USER root
RUN ["gem", "install", "fluent-plugin-elasticsearch", "fluent-plugin-detect-exceptions", "fluent-plugin-multi-format-parser", "--no-rdoc", "--no-ri"]
USER fluent
ENTRYPOINT ["fluentd", "-c", "/fluentd/etc/fluent.conf"]
