version: '3'
services:
   fluentd:
     build: ./fluentd
     user: root
     networks:
       - logging
     volumes:
       - ./fluentd/:/fluentd/etc
     links:
       - "elasticsearch"
     ports:
       - "24224:24224"
       - "24224:24224/udp"
     logging:
       driver: "json-file"
       options:
         max-size: "1G"
         max-file: "2"
     restart: always

   elasticsearch:
     image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
     networks:
       - logging
     ports:
       - "9200:9200"
       - "9300:9300"
     expose:
       - "9200"
     volumes:
       - 'es_data:/usr/share/elasticsearch/data'
       - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
     environment:
       - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
       - 'xpack.security.enabled=false'
       - 'discovery.type=single-node'
       - 'bootstrap.memory_lock=true'
       - 'node.master=true'
       - 'node.data=true'
       - 'node.ingest=true'
     logging:
       driver: fluentd
       options:
         fluentd-address: localhost:24224
         fluentd-async-connect: 'true'
         fluentd-retry-wait: '1s'
         fluentd-max-retries: '30'
         tag: els
     restart: always

   kibana:
     image: kibana:7.5.0
     networks:
       - logging
     links:
       - "elasticsearch"
     ports:
       - "5601:5601"
     volumes:
       - ./kibana.yml:/usr/share/kibana/config/kibana.yml
     logging:
       driver: fluentd
       options:
         fluentd-address: localhost:24224
         fluentd-async-connect: 'true'
         fluentd-retry-wait: '1s'
         fluentd-max-retries: '30'
         tag: kibana
     restart: always

networks:
  logging:
    driver: bridge

volumes:
  es_data:
    driver: local
